// Generated by CoffeeScript 1.6.2
(function() {
  var submitForm;

  submitForm = function(className, key, options) {
    className = "." + className;
    $.ajax({
      url: "http://kontactme.com/applications/" + key + "/messages",
      dataType: "json",
      type: "POST",
      data: {
        message: {
          email: $("[name=email]", className).val(),
          content: $("[name=content]", className).val(),
          title: $("[name=title]", className).val()
        },
        domain: window.location.hostname
      },
      success: function(response) {
        if (options.success) {
          return options.success(response);
        }
      },
      error: function(error) {
        if (options.error) {
          return options.error(JSON.parse(error.responseText).errors);
        }
      }
    });
    return false;
  };

  $.fn.kontactme = function(key, options) {
    return this.each(function(i) {
      var className;

      className = "kontactMe" + i;
      $(this).addClass(className);
      return $(this).on("submit", function() {
        return submitForm(className, key, options);
      });
    });
  };

}).call(this);
